"""init

Revision ID: 4353cf04f101
Revises: ce05a38e19ce
Create Date: 2025-06-04 23:04:32.953572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4353cf04f101'
down_revision: Union[str, None] = 'ce05a38e19ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bot', ['bot_link'])
    op.create_unique_constraint(None, 'bot', ['bot_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot', type_='unique')
    op.drop_constraint(None, 'bot', type_='unique')
    # ### end Alembic commands ###
